-- Creación de la tabla HISTORIAL_INCIDENTES
-- Ejecutar en PostgreSQL con un usuario con permisos de CREATE TABLE (ej. postgres)

CREATE TABLE IF NOT EXISTS HISTORIAL_INCIDENTES (
    ID_HISTORIAL SERIAL PRIMARY KEY,
    ID_INCIDENTE INTEGER NOT NULL,
    ESTADO_ANTERIOR TEXT,
    ESTADO_NUEVO TEXT NOT NULL,
    FECHA_CAMBIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO TEXT NOT NULL,
    COMENTARIO TEXT,
    TIPO_ACCION TEXT DEFAULT 'CAMBIO_ESTADO',
    DATOS_ADICIONALES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_INCIDENTE) REFERENCES INCIDENTES(ID_INCIDENTE)
);

-- Crear índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_historial_incidente ON HISTORIAL_INCIDENTES(ID_INCIDENTE);
