-- PROVEEDORES
CREATE TABLE IF NOT EXISTS PROVEEDORES (
    ID_PROVEEDOR INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PERSONA INTEGER NOT NULL UNIQUE,
    ESPECIALIDAD TEXT NOT NULL CHECK(ESPECIALIDAD IN ('Plomería', 'Electricidad', 'Obra Civil', 'Pintura', 'Cerrajería', 'Aseo', 'Otros')),
    CALIFICACION REAL DEFAULT 5.0 CHECK(CALIFICACION >= 0 AND CALIFICACION <= 5),
    OBSERVACIONES TEXT,
    ESTADO_REGISTRO INTEGER DEFAULT 1 CHECK(ESTADO_REGISTRO IN (0, 1)),
    CREATED_AT TEXT DEFAULT (datetime('now', 'localtime')),
    CREATED_BY TEXT,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA)
);

-- COTIZACIONES
CREATE TABLE IF NOT EXISTS COTIZACIONES (
    ID_COTIZACION INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_INCIDENTE INTEGER NOT NULL,
    ID_PROVEEDOR INTEGER NOT NULL,
    VALOR_MATERIALES INTEGER DEFAULT 0 CHECK(VALOR_MATERIALES >= 0),
    VALOR_MANO_OBRA INTEGER DEFAULT 0 CHECK(VALOR_MANO_OBRA >= 0),
    VALOR_TOTAL INTEGER NOT NULL CHECK(VALOR_TOTAL >= 0),
    DESCRIPCION_TRABAJO TEXT,
    DIAS_ESTIMADOS INTEGER DEFAULT 1,
    FECHA_COTIZACION TEXT DEFAULT (datetime('now', 'localtime')),
    ESTADO_COTIZACION TEXT DEFAULT 'Pendiente' CHECK(ESTADO_COTIZACION IN ('Pendiente', 'Aprobada', 'Rechazada')),
    CREATED_AT TEXT DEFAULT (datetime('now', 'localtime')),
    CREATED_BY TEXT,
    FOREIGN KEY (ID_INCIDENTE) REFERENCES INCIDENTES(ID_INCIDENTE),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

-- UPDATE INCIDENTES (Recreation to support new fields and statuses)
PRAGMA foreign_keys=off;

CREATE TABLE INCIDENTES_NEW (
    ID_INCIDENTE INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PROPIEDAD INTEGER NOT NULL,
    ID_CONTRATO_M INTEGER,
    DESCRIPCION_INCIDENTE TEXT NOT NULL,
    COSTO_INCIDENTE INTEGER DEFAULT 0 CHECK(COSTO_INCIDENTE >= 0),
    FECHA_INCIDENTE TEXT NOT NULL,
    PRIORIDAD TEXT DEFAULT 'Media' CHECK(PRIORIDAD IN ('Baja', 'Media', 'Alta', 'Urgente')),
    ORIGEN_REPORTE TEXT DEFAULT 'Inquilino' CHECK(ORIGEN_REPORTE IN ('Inquilino', 'Propietario', 'Inmobiliaria')),
    RESPONSABLE_PAGO TEXT CHECK(RESPONSABLE_PAGO IN ('Inquilino', 'Propietario', 'Inmobiliaria', 'Aseguradora')),
    ID_PROVEEDOR_ASIGNADO INTEGER,
    ID_COTIZACION_APROBADA INTEGER,
    QUIEN_ARREGLA TEXT, -- Legacy, kept for compatibility if needed, but ID_PROVEEDOR_ASIGNADO is preferred
    APROBADO_POR TEXT,
    FECHA_ARREGLO TEXT,
    ESTADO TEXT DEFAULT 'Reportado' CHECK(ESTADO IN ('Reportado', 'En Revision', 'Cotizado', 'Aprobado', 'En Reparacion', 'Finalizado', 'Cancelado')),
    DIAS_SIN_RESOLVER INTEGER DEFAULT 0,
    MOTIVO_CANCELACION TEXT,
    CREATED_AT TEXT DEFAULT (datetime('now', 'localtime')),
    CREATED_BY TEXT,
    UPDATED_AT TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATED_BY TEXT,
    FOREIGN KEY (ID_PROPIEDAD) REFERENCES PROPIEDADES(ID_PROPIEDAD),
    FOREIGN KEY (ID_CONTRATO_M) REFERENCES CONTRATOS_MANDATOS(ID_CONTRATO_M),
    FOREIGN KEY (ID_PROVEEDOR_ASIGNADO) REFERENCES PROVEEDORES(ID_PROVEEDOR),
    FOREIGN KEY (ID_COTIZACION_APROBADA) REFERENCES COTIZACIONES(ID_COTIZACION)
);

-- Copy data from old table if exists
INSERT INTO INCIDENTES_NEW (
    ID_INCIDENTE, ID_PROPIEDAD, ID_CONTRATO_M, DESCRIPCION_INCIDENTE, COSTO_INCIDENTE,
    FECHA_INCIDENTE, QUIEN_ARREGLA, APROBADO_POR, FECHA_ARREGLO, ESTADO,
    DIAS_SIN_RESOLVER, MOTIVO_CANCELACION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY
)
SELECT
    ID_INCIDENTE, ID_PROPIEDAD, ID_CONTRATO_M, DESCRIPCION_INCIDENTE, COSTO_INCIDENTE,
    FECHA_INCIDENTE, QUIEN_ARREGLA, APROBADO_POR, FECHA_ARREGLO,
    CASE ESTADO
        WHEN 'Pendiente' THEN 'Reportado'
        WHEN 'En Proceso' THEN 'En Reparacion'
        WHEN 'Resuelto' THEN 'Finalizado'
        ELSE ESTADO
    END,
    DIAS_SIN_RESOLVER, MOTIVO_CANCELACION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY
FROM INCIDENTES;

DROP TABLE INCIDENTES;

ALTER TABLE INCIDENTES_NEW RENAME TO INCIDENTES;

-- Recreate Indices for INCIDENTES
CREATE INDEX idx_incidentes_fecha ON INCIDENTES(ID_PROPIEDAD, FECHA_INCIDENTE);
CREATE INDEX idx_incidentes_estado ON INCIDENTES(ESTADO);
CREATE INDEX idx_incidentes_pendientes ON INCIDENTES(ESTADO, DIAS_SIN_RESOLVER) WHERE ESTADO IN ('Reportado', 'En Revision', 'Cotizado', 'Aprobado', 'En Reparacion');

PRAGMA foreign_keys=on;
