-- Corregir longitud de columna KEY para soportar prefijos + hash
ALTER TABLE IDEMPOTENCY_KEYS ALTER COLUMN KEY TYPE VARCHAR(128);
ALTER TABLE EVENTOS_IDEMPOTENCIA ALTER COLUMN IDEMPOTENCY_KEY TYPE VARCHAR(128);
