-- ============================================================
-- Migración: Agregar TODAS las columnas faltantes a PROPIEDADES
-- Fecha: 2026-04-06
-- Base de datos: PostgreSQL (Railway)
-- ============================================================
BEGIN;

-- === SERVICIOS PÚBLICOS ===
ALTER TABLE PROPIEDADES ADD COLUMN IF NOT EXISTS CODIGO_ENERGIA TEXT;
ALTER TABLE PROPIEDADES ADD COLUMN IF NOT EXISTS CODIGO_AGUA TEXT;
ALTER TABLE PROPIEDADES ADD COLUMN IF NOT EXISTS CODIGO_GAS TEXT;

-- === DATOS ADMINISTRACIÓN PH ===
ALTER TABLE PROPIEDADES ADD COLUMN IF NOT EXISTS TELEFONO_ADMINISTRACION TEXT;
ALTER TABLE PROPIEDADES ADD COLUMN IF NOT EXISTS TIPO_CUENTA_ADMINISTRACION TEXT;
ALTER TABLE PROPIEDADES ADD COLUMN IF NOT EXISTS NUMERO_CUENTA_ADMINISTRACION TEXT;

-- === CAMPOS DE PAGO ADMINISTRACIÓN ===
ALTER TABLE PROPIEDADES ADD COLUMN IF NOT EXISTS FECHA_PAGO_ADMINISTRACION INTEGER 
    CHECK (FECHA_PAGO_ADMINISTRACION BETWEEN 1 AND 28);
ALTER TABLE PROPIEDADES ADD COLUMN IF NOT EXISTS LINK_PAGO_ADMINISTRACION TEXT;
ALTER TABLE PROPIEDADES ADD COLUMN IF NOT EXISTS CUOTA_EXTRA_ORDINARIA NUMERIC(15,2) DEFAULT 0;

-- === NUEVO: OBSERVACIONES ADMIN PH ===
ALTER TABLE PROPIEDADES ADD COLUMN IF NOT EXISTS OBSERVACIONES_ADMIN_PH TEXT;

COMMIT;

-- === VERIFICACIÓN ===
-- SELECT column_name, data_type 
-- FROM information_schema.columns 
-- WHERE table_name = 'propiedades' 
-- ORDER BY column_name;
