-- Script de migración para corregir el FOREIGN KEY de LIQUIDACIONES_ASESORES
-- El problema: referencia a CONTRATOS_ARRENDAMIENTOS_OLD en lugar de CONTRATOS_ARRENDAMIENTOS

-- PASO 1: Deshabilitar foreign keys temporalmente
PRAGMA foreign_keys = OFF;

-- PASO 2: Crear tabla temporal con el schema correcto
CREATE TABLE LIQUIDACIONES_ASESORES_NEW (
    ID_LIQUIDACION_ASESOR INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_CONTRATO_A INTEGER NOT NULL,
    ID_ASESOR INTEGER NOT NULL,
    PERIODO_LIQUIDACION TEXT NOT NULL,
    CANON_ARRENDAMIENTO_LIQUIDADO INTEGER NOT NULL CHECK(CANON_ARRENDAMIENTO_LIQUIDADO > 0),
    PORCENTAJE_COMISION INTEGER NOT NULL CHECK(PORCENTAJE_COMISION >= 0 AND PORCENTAJE_COMISION <= 10000),
    COMISION_BRUTA INTEGER NOT NULL CHECK(COMISION_BRUTA >= 0),
    TOTAL_DESCUENTOS INTEGER DEFAULT 0 CHECK(TOTAL_DESCUENTOS >= 0),
    VALOR_NETO_ASESOR INTEGER NOT NULL,
    ESTADO_LIQUIDACION TEXT DEFAULT 'Pendiente' CHECK(ESTADO_LIQUIDACION IN ('Pendiente', 'Aprobada', 'Pagada', 'Anulada')),
    FECHA_CREACION TEXT DEFAULT (datetime('now', 'localtime')),
    FECHA_APROBACION TEXT,
    USUARIO_CREADOR TEXT,
    USUARIO_APROBADOR TEXT,
    OBSERVACIONES_LIQUIDACION TEXT,
    MOTIVO_ANULACION TEXT,
    CREATED_AT TEXT DEFAULT (datetime('now', 'localtime')),
    CREATED_BY TEXT,
    UPDATED_AT TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATED_BY TEXT,
    -- CORREGIDO: Ahora referencia a CONTRATOS_ARRENDAMIENTOS (sin _OLD)
    FOREIGN KEY (ID_CONTRATO_A) REFERENCES CONTRATOS_ARRENDAMIENTOS(ID_CONTRATO_A),
    FOREIGN KEY (ID_ASESOR) REFERENCES ASESORES(ID_ASESOR),
    UNIQUE(ID_CONTRATO_A, PERIODO_LIQUIDACION)
);

-- PASO 3: Copiar datos existentes (si los hay)
INSERT INTO LIQUIDACIONES_ASESORES_NEW
SELECT * FROM LIQUIDACIONES_ASESORES;

-- PASO 4: Eliminar tabla vieja
DROP TABLE LIQUIDACIONES_ASESORES;

-- PASO 5: Renombrar tabla nueva
ALTER TABLE LIQUIDACIONES_ASESORES_NEW RENAME TO LIQUIDACIONES_ASESORES;

-- PASO 6: Recrear índices
CREATE INDEX IF NOT EXISTS idx_liquidaciones_asesor ON LIQUIDACIONES_ASESORES(ID_ASESOR);
CREATE INDEX IF NOT EXISTS idx_liquidaciones_contrato ON LIQUIDACIONES_ASESORES(ID_CONTRATO_A);
CREATE INDEX IF NOT EXISTS idx_liquidaciones_periodo ON LIQUIDACIONES_ASESORES(PERIODO_LIQUIDACION);
CREATE INDEX IF NOT EXISTS idx_liquidaciones_estado ON LIQUIDACIONES_ASESORES(ESTADO_LIQUIDACION);

-- PASO 7: Reactivar foreign keys
PRAGMA foreign_keys = ON;
