-- Migración de datos bancarios y de consignatario de PROPIETARIOS a CONTRATOS_MANDATOS
-- Fecha: 2026-05-13

-- 1. Agregar columnas a CONTRATOS_MANDATOS
ALTER TABLE CONTRATOS_MANDATOS ADD COLUMN BANCO_PROPIETARIO TEXT;
ALTER TABLE CONTRATOS_MANDATOS ADD COLUMN NUMERO_CUENTA_PROPIETARIO TEXT;
ALTER TABLE CONTRATOS_MANDATOS ADD COLUMN TIPO_CUENTA TEXT CHECK(TIPO_CUENTA IN ('Ahorros', 'Corriente'));
ALTER TABLE CONTRATOS_MANDATOS ADD COLUMN CONSIGNATARIO TEXT;
ALTER TABLE CONTRATOS_MANDATOS ADD COLUMN DOCUMENTO_CONSIGNATARIO TEXT;

-- 2. Migrar datos existentes (donde exista un contrato de mandato para el propietario)
UPDATE CONTRATOS_MANDATOS cm
SET 
    BANCO_PROPIETARIO = p.BANCO_PROPIETARIO,
    NUMERO_CUENTA_PROPIETARIO = p.NUMERO_CUENTA_PROPIETARIO,
    TIPO_CUENTA = p.TIPO_CUENTA,
    CONSIGNATARIO = p.CONSIGNATARIO,
    DOCUMENTO_CONSIGNATARIO = p.DOCUMENTO_CONSIGNATARIO
FROM PROPIETARIOS p
WHERE cm.ID_PROPIETARIO = p.ID_PROPIETARIO;

-- 3. Eliminar columnas de PROPIETARIOS (Migración Estricta)
ALTER TABLE PROPIETARIOS DROP COLUMN BANCO_PROPIETARIO;
ALTER TABLE PROPIETARIOS DROP COLUMN NUMERO_CUENTA_PROPIETARIO;
ALTER TABLE PROPIETARIOS DROP COLUMN TIPO_CUENTA;
ALTER TABLE PROPIETARIOS DROP COLUMN CONSIGNATARIO;
ALTER TABLE PROPIETARIOS DROP COLUMN DOCUMENTO_CONSIGNATARIO;
