-- Archivo: migraciones/sql/migration_add_comision_contrato.sql
-- Fase 1: Extender esquema para soportar comisión por contrato individual

BEGIN;

-- 1. Agregar columnas a LIQUIDACIONES_CONTRATOS para desglose individual
ALTER TABLE LIQUIDACIONES_CONTRATOS
ADD COLUMN IF NOT EXISTS COMISION_PORCENTAJE_CONTRATO INTEGER NOT NULL DEFAULT 0;

ALTER TABLE LIQUIDACIONES_CONTRATOS
ADD COLUMN IF NOT EXISTS COMISION_MONTO_CONTRATO INTEGER NOT NULL DEFAULT 0;

-- 2. Agregar metadato de trazabilidad a LIQUIDACIONES_ASESORES
ALTER TABLE LIQUIDACIONES_ASESORES
ADD COLUMN IF NOT EXISTS MODO_COMISION TEXT DEFAULT 'ASESOR'
  CHECK(MODO_COMISION IN ('ASESOR', 'CONTRATO_MANDATO'));

-- 3. Agregar comentarios descriptivos
COMMENT ON COLUMN LIQUIDACIONES_CONTRATOS.COMISION_PORCENTAJE_CONTRATO
IS 'Porcentaje de comisión del ContratoMandato en escala 0-10000';
COMMENT ON COLUMN LIQUIDACIONES_CONTRATOS.COMISION_MONTO_CONTRATO
IS 'Comisión calculada: CANON_INCLUIDO * COMISION_PORCENTAJE_CONTRATO / 10000';

-- 4. Actualizar liquidaciones existentes para marcarlas como modo ASESOR (retrocompatibilidad)
UPDATE LIQUIDACIONES_ASESORES
SET MODO_COMISION = 'ASESOR'
WHERE MODO_COMISION IS NULL;

COMMIT;
