from typing import Any, List, Optional, Protocol
from src.dominio.entidades.usuario import Usuario
from src.dominio.entidades.sesion_usuario import SesionUsuario
from src.dominio.entidades.contrato_mandato import ContratoMandato
from src.dominio.entidades.contrato_arrendamiento import ContratoArrendamiento
from src.dominio.entidades.renovacion_contrato import RenovacionContrato
from src.dominio.entidades.propiedad import Propiedad
from src.dominio.entidades.ipc import IPC

class RepositorioUsuario(Protocol):
    """Interfaz para la persistencia de usuarios."""
    def obtener_por_nombre(self, nombre_usuario: str) -> Optional[Usuario]: ...
    def obtener_por_id(self, id_usuario: int) -> Optional[Usuario]: ...
    def crear(self, usuario: Usuario, usuario_sistema: str) -> Usuario: ...
    def actualizar(self, usuario: Usuario, usuario_sistema: str) -> bool: ...

class RepositorioSesion(Protocol):
    """Interfaz para la persistencia de sesiones."""
    def guardar(self, sesion: SesionUsuario) -> SesionUsuario: ...
    def obtener_por_token(self, token: str) -> Optional[SesionUsuario]: ...
    def finalizar_sesion(self, token: str) -> bool: ...

class RepositorioContratoMandato(Protocol):
    """Interfaz para la persistencia de contratos de mandato."""
    def crear(self, contrato: ContratoMandato, usuario: str) -> ContratoMandato: ...
    def obtener_por_id(self, id_contrato: int) -> Optional[ContratoMandato]: ...
    def obtener_activo_por_propiedad(self, id_propiedad: int) -> Optional[ContratoMandato]: ...
    def listar_todos(self) -> List[ContratoMandato]: ...
    def actualizar(self, contrato: ContratoMandato, usuario: str) -> bool: ...
    def listar_paginado(
        self,
        page: int = 1,
        page_size: int = 25,
        estado: Optional[str] = None,
        busqueda: Optional[str] = None,
        id_asesor: Optional[str] = None,
    ) -> Any: ...

class RepositorioContratoArrendamiento(Protocol):
    """Interfaz para la persistencia de contratos de arrendamiento."""
    def crear(self, contrato: ContratoArrendamiento, usuario: str) -> ContratoArrendamiento: ...
    def obtener_por_id(self, id_contrato: int) -> Optional[ContratoArrendamiento]: ...
    def obtener_activo_por_propiedad(self, id_propiedad: int) -> Optional[ContratoArrendamiento]: ...
    def listar_paginado(
        self,
        page: int = 1,
        page_size: int = 25,
        estado: Optional[str] = None,
        busqueda: Optional[str] = None,
        id_asesor: Optional[str] = None,
    ) -> Any: ...
    def actualizar(self, contrato: ContratoArrendamiento, usuario: str) -> bool: ...

class RepositorioPropiedad(Protocol):
    """Interfaz para la persistencia de propiedades."""
    def obtener_por_id(self, id_propiedad: int) -> Optional[Propiedad]: ...
    def actualizar(self, propiedad: Propiedad, usuario: str) -> bool: ...
    def listar_sin_mandato(self) -> List[dict]: ...
    def listar_para_arrendamiento(self) -> List[dict]: ...

class RepositorioRenovacion(Protocol):
    """Interfaz para la persistencia de renovaciones."""
    def crear(self, renovacion: RenovacionContrato, usuario: str) -> RenovacionContrato: ...

class RepositorioIPC(Protocol):
    """Interfaz para la persistencia de IPC."""
    def obtener_ultimo(self) -> Optional[IPC]: ...
