-- Migración para añadir campos de enlace_video y responsable_deposito a contratos

-- 1. Añadir campos a CONTRATOS_MANDATOS
ALTER TABLE CONTRATOS_MANDATOS
ADD COLUMN ENLACE_VIDEO TEXT,
ADD COLUMN RESPONSABLE_DEPOSITO_ID INTEGER;

-- 2. Añadir foreign key para responsable_deposito_id hacia ASESORES
ALTER TABLE CONTRATOS_MANDATOS
ADD CONSTRAINT fk_mandatos_responsable_deposito
FOREIGN KEY (RESPONSABLE_DEPOSITO_ID)
REFERENCES ASESORES(ID_ASESOR)
ON DELETE SET NULL;

-- 3. Añadir campo a CONTRATOS_ARRENDAMIENTOS
ALTER TABLE CONTRATOS_ARRENDAMIENTOS
ADD COLUMN ENLACE_VIDEO TEXT;
