-- Script de migración para PostgreSQL (Vistas Dashboard)

-- Vista: VW_ALERTA_VENCIMIENTO_CONTRATOS
CREATE OR REPLACE VIEW VW_ALERTA_VENCIMIENTO_CONTRATOS AS
SELECT 
    'ARRENDAMIENTO' AS TIPO_CONTRATO,
    ca.ID_CONTRATO_A AS ID_CONTRATO,
    ca.ID_PROPIEDAD,
    p.DIRECCION_PROPIEDAD AS DIRECCION,
    per.NOMBRE_COMPLETO AS INQUILINO_PROPIETARIO,
    ca.FECHA_FIN_CONTRATO_A AS FECHA_FIN,
    EXTRACT(DAY FROM AGE(ca.FECHA_FIN_CONTRATO_A::DATE, CURRENT_DATE))::INTEGER AS DIAS_RESTANTES
FROM CONTRATOS_ARRENDAMIENTOS ca
JOIN PROPIEDADES p ON ca.ID_PROPIEDAD = p.ID_PROPIEDAD
JOIN ARRENDATARIOS a ON ca.ID_ARRENDATARIO = a.ID_ARRENDATARIO
JOIN PERSONAS per ON a.ID_PERSONA = per.ID_PERSONA
WHERE ca.ESTADO_CONTRATO_A = 'ACTIVO'

UNION ALL

SELECT 
    'MANDATO' AS TIPO_CONTRATO,
    cm.ID_CONTRATO_M AS ID_CONTRATO,
    cm.ID_PROPIEDAD,
    p.DIRECCION_PROPIEDAD AS DIRECCION,
    per.NOMBRE_COMPLETO AS INQUILINO_PROPIETARIO,
    cm.FECHA_FIN_CONTRATO_M AS FECHA_FIN,
    EXTRACT(DAY FROM AGE(cm.FECHA_FIN_CONTRATO_M::DATE, CURRENT_DATE))::INTEGER AS DIAS_RESTANTES
FROM CONTRATOS_MANDATOS cm
JOIN PROPIEDADES p ON cm.ID_PROPIEDAD = p.ID_PROPIEDAD
JOIN PROPIETARIOS pr ON cm.ID_PROPIETARIO = pr.ID_PROPIETARIO
JOIN PERSONAS per ON pr.ID_PERSONA = per.ID_PERSONA
WHERE cm.ESTADO_CONTRATO_M = 'ACTIVO';


-- Vista: VW_ALERTA_MORA_DIARIA
CREATE OR REPLACE VIEW VW_ALERTA_MORA_DIARIA AS
SELECT 
    ca.ID_CONTRATO_A,
    per.NOMBRE_COMPLETO AS ARRENDATARIO,
    p.DIRECCION_PROPIEDAD AS PROPIEDAD,
    ca.CANON_ARRENDAMIENTO AS VALOR_RECAUDO,
    EXTRACT(DAY FROM AGE(CURRENT_DATE, (
        TO_CHAR(CURRENT_DATE, 'YYYY-MM') || '-' || LPAD(ca.DIA_PAGO::TEXT, 2, '0')
    )::DATE))::INTEGER AS DIAS_RETRASO
FROM CONTRATOS_ARRENDAMIENTOS ca
JOIN PROPIEDADES p ON ca.ID_PROPIEDAD = p.ID_PROPIEDAD
JOIN ARRENDATARIOS a ON ca.ID_ARRENDATARIO = a.ID_ARRENDATARIO
JOIN PERSONAS per ON a.ID_PERSONA = per.ID_PERSONA
WHERE ca.ESTADO_CONTRATO_A = 'ACTIVO'
AND EXTRACT(DAY FROM CURRENT_DATE) > ca.DIA_PAGO
AND NOT EXISTS (
    SELECT 1 
    FROM RECAUDOS r 
    WHERE r.ID_CONTRATO_A = ca.ID_CONTRATO_A 
    AND EXTRACT(MONTH FROM r.FECHA_PAGO::DATE) = EXTRACT(MONTH FROM CURRENT_DATE)
    AND EXTRACT(YEAR FROM r.FECHA_PAGO::DATE) = EXTRACT(YEAR FROM CURRENT_DATE)
    AND r.ESTADO_RECAUDO = 'Aplicado'
);

-- Índices de optimización para RECAUDOS
CREATE INDEX IF NOT EXISTS idx_recaudos_fecha_pago ON RECAUDOS(FECHA_PAGO);
CREATE INDEX IF NOT EXISTS idx_recaudos_estado ON RECAUDOS(ESTADO_RECAUDO);
