-- Alteración de esquema para permitir liquidaciones multi-contrato
-- Autor: Gemini CLI
-- Fecha: 2026-05-11

-- 1. Permitir nulos en ID_CONTRATO_A para liquidaciones globales
ALTER TABLE LIQUIDACIONES_ASESORES ALTER COLUMN ID_CONTRATO_A DROP NOT NULL;

-- 2. Asegurar que el total de bonificaciones sea BIGINT para evitar overflow monetario
-- (Siguiendo el estándar de otros campos monetarios en PostgreSQL)
ALTER TABLE LIQUIDACIONES_ASESORES ALTER COLUMN TOTAL_BONIFICACIONES TYPE BIGINT;
ALTER TABLE LIQUIDACIONES_ASESORES ALTER COLUMN COMISION_BRUTA TYPE BIGINT;
ALTER TABLE LIQUIDACIONES_ASESORES ALTER COLUMN TOTAL_DESCUENTOS TYPE BIGINT;
ALTER TABLE LIQUIDACIONES_ASESORES ALTER COLUMN VALOR_NETO_ASESOR TYPE BIGINT;
ALTER TABLE LIQUIDACIONES_ASESORES ALTER COLUMN CANON_ARRENDAMIENTO_LIQUIDADO TYPE BIGINT;

COMMENT ON COLUMN LIQUIDACIONES_ASESORES.ID_CONTRATO_A IS 'NULL para liquidaciones globales (multi-contrato)';
