"""
Interface (Protocol): Repositorio de Recaudos
"""
from typing import List, Optional, Protocol, Any, Dict
from src.dominio.entidades.recaudo import Recaudo
from src.dominio.entidades.recaudo_concepto import RecaudoConcepto

class IRepositorioRecaudo(Protocol):
    def obtener_por_id(self, id_recaudo: int) -> Optional[Recaudo]: ...
    def listar_por_contrato(self, id_contrato_a: int) -> List[Recaudo]: ...
    def listar_todos(self) -> List[Recaudo]: ...
    def crear(self, recaudo: Recaudo, conceptos: List[RecaudoConcepto], usuario_sistema: str) -> Recaudo: ...
    def cambiar_estado(self, id_recaudo: int, nuevo_estado: str, usuario_sistema: str) -> bool: ...
    def obtener_conceptos_por_recaudo(self, id_recaudo: int) -> List[RecaudoConcepto]: ...
    def listar_paginado(self, limit: int, offset: int, estado: Optional[str] = None, fecha_desde: Optional[str] = None, fecha_hasta: Optional[str] = None, busqueda: Optional[str] = None) -> List[Dict[str, Any]]: ...
    def contar_con_filtros(self, estado: Optional[str] = None, fecha_desde: Optional[str] = None, fecha_hasta: Optional[str] = None, busqueda: Optional[str] = None) -> int: ...
