"""
Interface (Protocol): Repositorio de Propietarios
"""
from typing import List, Optional, Protocol, Any
from src.dominio.entidades.propietario import Propietario

class IRepositorioPropietario(Protocol):
    def obtener_por_id(self, id_propietario: int) -> Optional[Propietario]: ...
    def obtener_por_persona(self, id_persona: int) -> Optional[Propietario]: ...
    def crear(self, propietario: Propietario, usuario_sistema: str) -> Propietario: ...
    def actualizar(self, propietario: Propietario, usuario_sistema: str) -> bool: ...
    def eliminar_por_persona(self, id_persona: int) -> bool: ...
