"""
Interface (Protocol): Repositorio de Liquidaciones
"""
from typing import List, Optional, Protocol, Any, Dict
from src.dominio.entidades.liquidacion import Liquidacion

class IRepositorioLiquidacion(Protocol):
    def obtener_por_id(self, id_liquidacion: int) -> Optional[Liquidacion]: ...
    def obtener_por_contrato_y_periodo(self, id_contrato_m: int, periodo: str) -> Optional[Liquidacion]: ...
    def crear(self, liquidacion: Liquidacion, usuario_sistema: str) -> Liquidacion: ...
    def listar_todas(self) -> List[Dict[str, Any]]: ...
    def aprobar(self, id_liquidacion: int, usuario_sistema: str) -> None: ...
    def marcar_como_pagada(self, id_liquidacion: int, fecha_pago: str, metodo_pago: str, referencia_pago: str, usuario_sistema: str) -> None: ...
    def cancelar(self, id_liquidacion: int, motivo: str, usuario_sistema: str) -> None: ...
    def reversar(self, id_liquidacion: int, usuario_sistema: str) -> None: ...
    def cancelar_masivamente(self, ids: List[int], motivo: str, usuario_sistema: str) -> Dict[str, List[int]]: ...
    def reversar_masivamente(self, ids: List[int], usuario_sistema: str) -> Dict[str, List[int]]: ...
    def cancelar_por_propietario_y_periodo(self, id_prop: int, periodo: str, motivo: str, usr: str) -> int: ...
    def reversar_por_propietario_y_periodo(self, id_prop: int, periodo: str, usr: str) -> int: ...
    def aprobar_por_propietario_y_periodo(self, id_propietario: int, periodo: str, usuario_sistema: str) -> int: ...
    def marcar_como_pagadas_por_propietario(self, id_propietario: int, periodo: str, fecha_pago: str, metodo_pago: str, referencia_pago: str, usuario_sistema: str) -> int: ...
    def listar_agrupadas_por_propietario_paginado(self, page: int = 1, page_size: int = 25, estado: Optional[str] = None, periodo: Optional[str] = None, busqueda: Optional[str] = None) -> Any: ...
    def listar_paginado(self, limit: int, offset: int, estado: Optional[str] = None, periodo: Optional[str] = None, busqueda: Optional[str] = None) -> List[Dict[str, Any]]: ...
    def contar_con_filtros(self, estado: Optional[str] = None, periodo: Optional[str] = None, busqueda: Optional[str] = None) -> int: ...
    def _row_to_entity(self, row: Any) -> Liquidacion: ...
