from typing import Protocol, List, Optional

from ..entidades.cotizacion import Cotizacion


class RepositorioCotizaciones(Protocol):
    def guardar(self, cotizacion: Cotizacion) -> int: ...

    def obtener_por_incidente(self, id_incidente: int) -> List[Cotizacion]: ...

    def obtener_por_id(self, id_cotizacion: int) -> Optional[Cotizacion]: ...

    def actualizar(self, cotizacion: Cotizacion) -> None: ...

    def eliminar(self, id_cotizacion: int) -> None: ...
