"""
Interface (Protocol): Repositorio de Asesores
"""
from typing import List, Optional, Protocol, Any
from src.dominio.entidades.asesor import Asesor

class IRepositorioAsesor(Protocol):
    def obtener_por_id(self, id_asesor: int) -> Optional[Asesor]: ...
    def obtener_por_persona(self, id_persona: int) -> Optional[Asesor]: ...
    def listar_activos(self) -> List[Asesor]: ...
    def listar_todos(self) -> List[Asesor]: ...
    def crear(self, asesor: Asesor, usuario_sistema: str) -> Asesor: ...
    def actualizar(self, asesor: Asesor, usuario_sistema: str) -> bool: ...
    def eliminar_por_persona(self, id_persona: int) -> bool: ...
