"""
Interface (Protocol): Repositorio de Arrendatarios
"""
from typing import List, Optional, Protocol, Any
from src.dominio.entidades.arrendatario import Arrendatario

class IRepositorioArrendatario(Protocol):
    def obtener_por_id(self, id_arrendatario: int) -> Optional[Arrendatario]: ...
    def obtener_por_persona(self, id_persona: int) -> Optional[Arrendatario]: ...
    def crear(self, arrendatario: Arrendatario, usuario_sistema: str) -> Arrendatario: ...
    def actualizar(self, arrendatario: Arrendatario, usuario_sistema: str) -> bool: ...
    def eliminar_por_persona(self, id_persona: int) -> bool: ...
