from typing import List, Optional, Protocol

from ..entidades.proveedor import Proveedor


class RepositorioProveedores(Protocol):
    def obtener_por_id(self, id_proveedor: int) -> Optional[Proveedor]: ...

    def obtener_por_persona_id(self, id_persona: int) -> Optional[Proveedor]: ...

    def listar(self, especialidad: Optional[str] = None) -> List[Proveedor]: ...

    def guardar(self, proveedor: Proveedor) -> int: ...

    def actualizar(self, proveedor: Proveedor) -> None: ...

    def eliminar(self, id_proveedor: int) -> None: ...
    def eliminar_por_persona(self, id_persona: int) -> bool: ...
