"""
Interface (Protocol): Repositorio de Dashboard
"""
from typing import List, Protocol, Any, Dict, Optional

class IRepositorioDashboard(Protocol):
    def obtener_resumen_mora(self) -> Dict: ...
    def obtener_top_morosos(self, limit: int = 5) -> List[Dict]: ...
    def obtener_total_recaudado(self, mes: str, anio: str, id_asesor: Optional[int] = None) -> float: ...
    def obtener_total_esperado(self, id_asesor: Optional[int] = None) -> float: ...
    def obtener_conteo_vencimientos_rangos(self) -> Dict: ...
    def obtener_lista_vencimientos(self, dias: int) -> List[Dict]: ...
    def obtener_contratos_elegibles_ipc(self, dias: int) -> List[Dict]: ...
    def obtener_comisiones_pendientes(self, id_asesor: Optional[int] = None) -> Dict: ...
    def obtener_metricas_ocupacion(self, id_asesor: Optional[int] = None) -> Dict: ...
    def obtener_propiedades_por_tipo(self, id_asesor: Optional[int] = None) -> Dict[str, int]: ...
    def obtener_metricas_expertas(self, id_asesor: Optional[int] = None) -> Dict[str, float]: ...
    def obtener_top_asesores_revenue(self) -> List[Dict]: ...
    def obtener_tunel_vencimientos(self) -> List[Dict]: ...
    def obtener_metricas_incidentes(self) -> Dict: ...
    def obtener_total_contratos_activos(self, id_asesor: Optional[int] = None) -> int: ...
    def obtener_morosidad_por_zona(self) -> Dict: ...
    def obtener_desempeno_asesores(self) -> Dict: ...
    def obtener_recibos_vencidos_resumen(self) -> Dict: ...
