CREATE TABLE IF NOT EXISTS BONIFICACIONES_ASESORES (
    ID_BONIFICACION_ASESOR INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_LIQUIDACION_ASESOR INTEGER NOT NULL,
    TIPO_BONIFICACION TEXT NOT NULL,
    DESCRIPCION_BONIFICACION TEXT,
    VALOR_BONIFICACION INTEGER NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY TEXT,
    FOREIGN KEY (ID_LIQUIDACION_ASESOR) REFERENCES LIQUIDACIONES_ASESORES(ID_LIQUIDACION_ASESOR)
);
