-- Migration 004: Create CUOTA_INCIDENTE table
-- Feature: 003-integracion-incidentes-liquidaciones
-- Date: 2026-06-30

CREATE TABLE IF NOT EXISTS CUOTA_INCIDENTE (
    ID_CUOTA INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PLAN_PAGO INTEGER NOT NULL,
    NUMERO_CUOTA INTEGER NOT NULL CHECK(NUMERO_CUOTA > 0),
    VALOR_CUOTA INTEGER NOT NULL CHECK(VALOR_CUOTA > 0),
    ID_LIQUIDACION INTEGER,
    ESTADO_PAGO TEXT NOT NULL DEFAULT 'Pendiente' CHECK(ESTADO_PAGO IN ('Pendiente', 'Asociada', 'Pagada')),
    CREATED_AT TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    FOREIGN KEY (ID_PLAN_PAGO) REFERENCES PLAN_PAGO_INCIDENTE(ID_PLAN_PAGO) ON DELETE CASCADE,
    FOREIGN KEY (ID_LIQUIDACION) REFERENCES LIQUIDACIONES(ID_LIQUIDACION),
    UNIQUE(ID_PLAN_PAGO, NUMERO_CUOTA) -- One installment number per plan
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS IDX_CUOTA_PLAN_PAGO ON CUOTA_INCIDENTE(ID_PLAN_PAGO);
CREATE INDEX IF NOT EXISTS IDX_CUOTA_LIQUIDACION ON CUOTA_INCIDENTE(ID_LIQUIDACION);
CREATE INDEX IF NOT EXISTS IDX_CUOTA_ESTADO ON CUOTA_INCIDENTE(ESTADO_PAGO);
CREATE INDEX IF NOT EXISTS IDX_CUOTA_NUMERO ON CUOTA_INCIDENTE(NUMERO_CUOTA);

-- Add trigger to validate installment state transitions
CREATE TRIGGER IF NOT EXISTS TRG_CUOTA_VALIDAR_TRANSICION
AFTER UPDATE ON CUOTA_INCIDENTE
BEGIN
    SELECT CASE
        WHEN OLD.ESTADO_PAGO = 'Pendiente' AND NEW.ESTADO_PAGO NOT IN ('Asociada')
        THEN RAISE(ABORT, 'Invalid state transition from Pendiente')
        WHEN OLD.ESTADO_PAGO = 'Asociada' AND NEW.ESTADO_PAGO NOT IN ('Pendiente', 'Pagada')
        THEN RAISE(ABORT, 'Invalid state transition from Asociada')
        WHEN OLD.ESTADO_PAGO = 'Pagada' AND NEW.ESTADO_PAGO NOT IN ('Asociada')
        THEN RAISE(ABORT, 'Invalid state transition from Pagada')
    END;
END;
