-- Migration 006: Create additional database indexes for performance
-- Feature: 003-integracion-incidentes-liquidaciones
-- Date: 2026-06-30

-- Composite indexes for common query patterns
CREATE INDEX IF NOT EXISTS IDX_INCIDENTES_ESTADO_PAGO_ID ON INCIDENTES(ID_INCIDENTE, estado_pago);
CREATE INDEX IF NOT EXISTS IDX_INCIDENTES_PROPIEDAD_ESTADO ON INCIDENTES(ID_PROPIEDAD, estado);
CREATE INDEX IF NOT EXISTS IDX_LIQUIDACIONES_CONTRATO_PERIODO ON LIQUIDACIONES(ID_CONTRATO_M, periodo);
CREATE INDEX IF NOT EXISTS IDX_LIQUIDACIONES_ESTADO_PAGO ON LIQUIDACIONES(estado_liquidacion, valor_incidentes);

-- Indexes for JOIN operations
CREATE INDEX IF NOT EXISTS IDX_PLAN_PAGO_INCIDENTE_ID_ESTADO ON PLAN_PAGO_INCIDENTE(ID_INCIDENTE, ESTADO);
CREATE INDEX IF NOT EXISTS IDX_CUOTA_PLAN_PAGO_ESTADO ON CUOTA_INCIDENTE(ID_PLAN_PAGO, ESTADO_PAGO);
CREATE INDEX IF NOT EXISTS IDX_INCIDENTE_LIQ_INCIDENTE_CUOTA ON INCIDENTE_LIQUIDACION(ID_INCIDENTE, NUMERO_CUOTA);

-- Indexes for reporting queries
CREATE INDEX IF NOT EXISTS IDX_INCIDENTES_CREATED_AT ON INCIDENTES(CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_LIQUIDACIONES_CREATED_AT ON LIQUIDACIONES(CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_PLAN_PAGO_CREATED_AT ON PLAN_PAGO_INCIDENTE(CREATED_AT);

-- Partial indexes for common filtered queries
CREATE INDEX IF NOT EXISTS IDX_INCIDENTES_PENDIENTES_PAGO ON INCIDENTES(ID_INCIDENTE) 
WHERE estado_pago = 'Pendiente';

CREATE INDEX IF NOT EXISTS IDX_LIQUIDACIONES_CON_INCIDENTES ON LIQUIDACIONES(ID_LIQUIDACION) 
WHERE valor_incidentes > 0;

CREATE INDEX IF NOT EXISTS IDX_PLAN_PAGO_ACTIVOS ON PLAN_PAGO_INCIDENTE(ID_INCIDENTE) 
WHERE ESTADO = 'Activo';

-- Analyze tables for query optimizer
ANALYZE INCIDENTES;
ANALYZE LIQUIDACIONES;
ANALYZE PLAN_PAGO_INCIDENTE;
ANALYZE CUOTA_INCIDENTE;
ANALYZE INCIDENTE_LIQUIDACION;
