-- PASO 1: Corregir arrendamientos existentes
-- Actualizar fecha_pago al día real de fecha_inicio
UPDATE CONTRATOS_ARRENDAMIENTOS ca
SET FECHA_PAGO = CAST(
    EXTRACT(DAY FROM TO_DATE(ca.FECHA_INICIO_CONTRATO_A, 'YYYY-MM-DD')) AS TEXT
)
WHERE ca.ESTADO_CONTRATO_A IN ('ACTIVO', 'Activo');

-- PASO 2: Corregir mandatos grupo 3 existentes (21-31)
-- Poner "-1" como sentinel de "último día del mes"
UPDATE CONTRATOS_MANDATOS cm
SET FECHA_PAGO = '-1'
WHERE cm.ESTADO_CONTRATO_M = 'Activo'
  AND cm.GRUPO_OPERATIVO = 3;

-- PASO 3: Verificar resultados
SELECT 
    'MANDATO' as TIPO,
    COUNT(*) as TOTAL,
    SUM(CASE WHEN FECHA_PAGO = '10' THEN 1 ELSE 0 END) as G1_DIA_10,
    SUM(CASE WHEN FECHA_PAGO = '20' THEN 1 ELSE 0 END) as G2_DIA_20,
    SUM(CASE WHEN FECHA_PAGO = '-1' THEN 1 ELSE 0 END) as G3_FIN_MES,
    SUM(CASE WHEN FECHA_PAGO NOT IN ('10', '20', '-1') THEN 1 ELSE 0 END) as INVALIDOS
FROM CONTRATOS_MANDATOS
WHERE ESTADO_CONTRATO_M = 'Activo'
UNION ALL
SELECT
    'ARRENDAMIENTO',
    COUNT(*),
    NULL, NULL, NULL,
    SUM(CASE WHEN FECHA_PAGO IS NULL OR FECHA_PAGO = '' THEN 1 ELSE 0 END)
FROM CONTRATOS_ARRENDAMIENTOS
WHERE ESTADO_CONTRATO_A IN ('ACTIVO', 'Activo');
