-- Migration 003: Create PLAN_PAGO_INCIDENTE table
-- Feature: 003-integracion-incidentes-liquidaciones
-- Date: 2026-06-30

CREATE TABLE IF NOT EXISTS PLAN_PAGO_INCIDENTE (
    ID_PLAN_PAGO INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_INCIDENTE INTEGER NOT NULL,
    NUM_CUOTAS INTEGER NOT NULL CHECK(NUM_CUOTAS > 0),
    VALOR_CUOTA INTEGER NOT NULL CHECK(VALOR_CUOTA > 0),
    TOTAL_PLAN INTEGER NOT NULL,
    ESTADO TEXT NOT NULL DEFAULT 'Activo' CHECK(ESTADO IN ('Activo', 'Completado', 'Cancelado')),
    CREADO_POR TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    UPDATED_AT TEXT,
    FOREIGN KEY (ID_INCIDENTE) REFERENCES INCIDENTES(ID_INCIDENTE),
    UNIQUE(ID_INCIDENTE) -- Only one active plan per incident
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS IDX_PLAN_PAGO_INCIDENTE ON PLAN_PAGO_INCIDENTE(ID_INCIDENTE);
CREATE INDEX IF NOT EXISTS IDX_PLAN_PAGO_ESTADO ON PLAN_PAGO_INCIDENTE(ESTADO);
CREATE INDEX IF NOT EXISTS IDX_PLAN_PAGO_CREADO_POR ON PLAN_PAGO_INCIDENTE(CREADO_POR);

-- Add trigger to validate total_plan = num_cuotas * valor_cuota
CREATE TRIGGER IF NOT EXISTS TRG_PLAN_PAGO_VALIDAR_TOTAL
AFTER INSERT ON PLAN_PAGO_INCIDENTE
BEGIN
    SELECT CASE
        WHEN NEW.TOTAL_PLAN != NEW.NUM_CUOTAS * NEW.VALOR_CUOTA
        THEN RAISE(ABORT, 'TOTAL_PLAN must equal NUM_CUOTAS * VALOR_CUOTA')
    END;
END;
