-- Migration 005: Create INCIDENTE_LIQUIDACION table
-- Feature: 003-integracion-incidentes-liquidaciones
-- Date: 2026-06-30

CREATE TABLE IF NOT EXISTS INCIDENTE_LIQUIDACION (
    ID_RELACION INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_INCIDENTE INTEGER NOT NULL,
    ID_LIQUIDACION INTEGER NOT NULL,
    NUMERO_CUOTA INTEGER NOT NULL,
    VALOR_DESCUENTO INTEGER NOT NULL CHECK(VALOR_DESCUENTO > 0),
    ASOCIADO_POR TEXT NOT NULL,
    FECHA_ASOCIACION TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    FOREIGN KEY (ID_INCIDENTE) REFERENCES INCIDENTES(ID_INCIDENTE),
    FOREIGN KEY (ID_LIQUIDACION) REFERENCES LIQUIDACIONES(ID_LIQUIDACION),
    UNIQUE(ID_INCIDENTE, ID_LIQUIDACION, NUMERO_CUOTA) -- Prevent duplicate associations
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS IDX_INCIDENTE_LIQ_INCIDENTE ON INCIDENTE_LIQUIDACION(ID_INCIDENTE);
CREATE INDEX IF NOT EXISTS IDX_INCIDENTE_LIQ_LIQUIDACION ON INCIDENTE_LIQUIDACION(ID_LIQUIDACION);
CREATE INDEX IF NOT EXISTS IDX_INCIDENTE_LIQ_CUOTA ON INCIDENTE_LIQUIDACION(NUMERO_CUOTA);
CREATE INDEX IF NOT EXISTS IDX_INCIDENTE_LIQ_FECHA ON INCIDENTE_LIQUIDACION(FECHA_ASOCIACION);

-- Add trigger to prevent duplicate installment associations
CREATE TRIGGER IF NOT EXISTS TRG_INCIDENTE_LIQ_PREVENIR_DUPLICADO
BEFORE INSERT ON INCIDENTE_LIQUIDACION
BEGIN
    SELECT CASE
        WHEN EXISTS (
            SELECT 1 FROM INCIDENTE_LIQUIDACION 
            WHERE ID_INCIDENTE = NEW.ID_INCIDENTE 
            AND NUMERO_CUOTA = NEW.NUMERO_CUOTA
        )
        THEN RAISE(ABORT, 'Installment already associated to a liquidation')
    END;
END;

-- Add trigger to update liquidation valor_incidentes on insert
CREATE TRIGGER IF NOT EXISTS TRG_INCIDENTE_LIQ_ACTUALIZAR_VALOR_INSERT
AFTER INSERT ON INCIDENTE_LIQUIDACION
BEGIN
    UPDATE LIQUIDACIONES 
    SET valor_incidentes = (
        SELECT COALESCE(SUM(VALOR_DESCUENTO), 0)
        FROM INCIDENTE_LIQUIDACION
        WHERE ID_LIQUIDACION = NEW.ID_LIQUIDACION
    )
    WHERE ID_LIQUIDACION = NEW.ID_LIQUIDACION;
END;

-- Add trigger to update liquidation valor_incidentes on delete
CREATE TRIGGER IF NOT EXISTS TRG_INCIDENTE_LIQ_ACTUALIZAR_VALOR_DELETE
AFTER DELETE ON INCIDENTE_LIQUIDACION
BEGIN
    UPDATE LIQUIDACIONES 
    SET valor_incidentes = (
        SELECT COALESCE(SUM(VALOR_DESCUENTO), 0)
        FROM INCIDENTE_LIQUIDACION
        WHERE ID_LIQUIDACION = OLD.ID_LIQUIDACION
    )
    WHERE ID_LIQUIDACION = OLD.ID_LIQUIDACION;
END;
