-- Script para vaciar las tablas solicitadas
-- Se desactivan las llaves foráneas para evitar errores de restricción durante el borrado

PRAGMA foreign_keys = OFF;

BEGIN TRANSACTION;

DELETE FROM PERSONAS;
DELETE FROM PROPIETARIOS;
DELETE FROM ARRENDATARIOS;
DELETE FROM ASESORES;
DELETE FROM PROPIEDADES;
-- Corregido: CONTRATO_MANDATOS -> CONTRATOS_MANDATOS
DELETE FROM CONTRATOS_MANDATOS;
-- Corregido: CONTRATOS_ARRENDAMIENTO -> CONTRATOS_ARRENDAMIENTOS
DELETE FROM CONTRATOS_ARRENDAMIENTOS;
DELETE FROM SEGUROS;
DELETE FROM RENOVACIONES_CONTRATOS;
DELETE FROM SALDOS_FAVOR;
DELETE FROM RECIBOS_PUBLICOS;
DELETE FROM RECAUDOS;
DELETE FROM PAGOS_ASESORES;
DELETE FROM LIQUIDACIONES_CONTRATOS;
DELETE FROM LIQUIDACIONES_ASESORES;
DELETE FROM LIQUIDACIONES;
DELETE FROM INCIDENTES;
DELETE FROM HISTORIAL_INCIDENTES;
DELETE FROM DOCUMENTOS;
DELETE FROM DESCUENTOS_ASESORES;
DELETE FROM COTIZACIONES;
DELETE FROM CODEUDORES;

COMMIT;

PRAGMA foreign_keys = ON;
VACUUM;
