"""
Scripts SQL para creacion de Triggers de Auditoria.
Implementa auditoria automatica a nivel de base de datos.

ESQUEMA REAL DE AUDITORIA_CAMBIOS:
- ID_AUDITORIA (PK)
- TABLA
- ID_REGISTRO
- TIPO_OPERACION
- CAMPO_MODIFICADO
- VALOR_ANTERIOR
- VALOR_NUEVO
- USUARIO
- FECHA_CAMBIO
- MOTIVO_CAMBIO
- IP_ORIGEN
"""

# Trigger para auditoria de USUARIOS - UPDATE
TRIGGER_USUARIOS_UPDATE = """
CREATE TRIGGER IF NOT EXISTS trg_audit_usuarios_update
AFTER UPDATE ON USUARIOS
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_CAMBIOS (TABLA, ID_REGISTRO, TIPO_OPERACION, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO, FECHA_CAMBIO)
    SELECT 'USUARIOS', NEW.ID_USUARIO, 'UPDATE', 'ESTADO_USUARIO', CAST(OLD.ESTADO_USUARIO AS TEXT), CAST(NEW.ESTADO_USUARIO AS TEXT), NEW.UPDATED_BY, datetime('now', 'localtime')
    WHERE OLD.ESTADO_USUARIO != NEW.ESTADO_USUARIO
    UNION ALL
    SELECT 'USUARIOS', NEW.ID_USUARIO, 'UPDATE', 'ROL', OLD.ROL, NEW.ROL, NEW.UPDATED_BY, datetime('now', 'localtime')
    WHERE OLD.ROL != NEW.ROL;
END;
"""

# Trigger para auditoria de PERSONAS - UPDATE
TRIGGER_PERSONAS_UPDATE = """
CREATE TRIGGER IF NOT EXISTS trg_audit_personas_update
AFTER UPDATE ON PERSONAS
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_CAMBIOS (TABLA, ID_REGISTRO, TIPO_OPERACION, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO, FECHA_CAMBIO)
    SELECT 'PERSONAS', NEW.ID_PERSONA, 'UPDATE', 'NOMBRE_COMPLETO', OLD.NOMBRE_COMPLETO, NEW.NOMBRE_COMPLETO, NEW.UPDATED_BY, datetime('now', 'localtime')
    WHERE OLD.NOMBRE_COMPLETO != NEW.NOMBRE_COMPLETO
    UNION ALL
    SELECT 'PERSONAS', NEW.ID_PERSONA, 'UPDATE', 'TELEFONO_PRINCIPAL', OLD.TELEFONO_PRINCIPAL, NEW.TELEFONO_PRINCIPAL, NEW.UPDATED_BY, datetime('now', 'localtime')
    WHERE OLD.TELEFONO_PRINCIPAL != NEW.TELEFONO_PRINCIPAL
    UNION ALL
    SELECT 'PERSONAS', NEW.ID_PERSONA, 'UPDATE', 'CORREO_ELECTRONICO', OLD.CORREO_ELECTRONICO, NEW.CORREO_ELECTRONICO, NEW.UPDATED_BY, datetime('now', 'localtime')
    WHERE OLD.CORREO_ELECTRONICO != NEW.CORREO_ELECTRONICO
    UNION ALL
    SELECT 'PERSONAS', NEW.ID_PERSONA, 'UPDATE', 'ESTADO_REGISTRO', CAST(OLD.ESTADO_REGISTRO AS TEXT), CAST(NEW.ESTADO_REGISTRO AS TEXT), NEW.UPDATED_BY, datetime('now', 'localtime')
    WHERE OLD.ESTADO_REGISTRO != NEW.ESTADO_REGISTRO;
END;
"""

# Trigger para auditoria de PROPIEDADES - UPDATE
TRIGGER_PROPIEDADES_UPDATE = """
CREATE TRIGGER IF NOT EXISTS trg_audit_propiedades_update
AFTER UPDATE ON PROPIEDADES
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_CAMBIOS (TABLA, ID_REGISTRO, TIPO_OPERACION, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO, FECHA_CAMBIO)
    SELECT 'PROPIEDADES', NEW.ID_PROPIEDAD, 'UPDATE', 'DISPONIBILIDAD_PROPIEDAD', CAST(OLD.DISPONIBILIDAD_PROPIEDAD AS TEXT), CAST(NEW.DISPONIBILIDAD_PROPIEDAD AS TEXT), NEW.UPDATED_BY, datetime('now', 'localtime')
    WHERE OLD.DISPONIBILIDAD_PROPIEDAD != NEW.DISPONIBILIDAD_PROPIEDAD
    UNION ALL
    SELECT 'PROPIEDADES', NEW.ID_PROPIEDAD, 'UPDATE', 'CANON_ARRENDAMIENTO_ESTIMADO', CAST(OLD.CANON_ARRENDAMIENTO_ESTIMADO AS TEXT), CAST(NEW.CANON_ARRENDAMIENTO_ESTIMADO AS TEXT), NEW.UPDATED_BY, datetime('now', 'localtime')
    WHERE OLD.CANON_ARRENDAMIENTO_ESTIMADO != NEW.CANON_ARRENDAMIENTO_ESTIMADO
    UNION ALL
    SELECT 'PROPIEDADES', NEW.ID_PROPIEDAD, 'UPDATE', 'ESTADO_REGISTRO', CAST(OLD.ESTADO_REGISTRO AS TEXT), CAST(NEW.ESTADO_REGISTRO AS TEXT), NEW.UPDATED_BY, datetime('now', 'localtime')
    WHERE OLD.ESTADO_REGISTRO != NEW.ESTADO_REGISTRO;
END;
"""

# Trigger para auditoria de CONTRATOS_ARRENDAMIENTOS - UPDATE
TRIGGER_CONTRATOS_UPDATE = """
CREATE TRIGGER IF NOT EXISTS trg_audit_contratos_update
AFTER UPDATE ON CONTRATOS_ARRENDAMIENTOS
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_CAMBIOS (TABLA, ID_REGISTRO, TIPO_OPERACION, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO, FECHA_CAMBIO)
    SELECT 'CONTRATOS_ARRENDAMIENTOS', NEW.ID_CONTRATO_A, 'UPDATE', 'CANON_ARRENDAMIENTO', CAST(OLD.CANON_ARRENDAMIENTO AS TEXT), CAST(NEW.CANON_ARRENDAMIENTO AS TEXT), NEW.UPDATED_BY, datetime('now', 'localtime')
    WHERE OLD.CANON_ARRENDAMIENTO != NEW.CANON_ARRENDAMIENTO
    UNION ALL
    SELECT 'CONTRATOS_ARRENDAMIENTOS', NEW.ID_CONTRATO_A, 'UPDATE', 'ESTADO_CONTRATO_A', OLD.ESTADO_CONTRATO_A, NEW.ESTADO_CONTRATO_A, NEW.UPDATED_BY, datetime('now', 'localtime')
    WHERE OLD.ESTADO_CONTRATO_A != NEW.ESTADO_CONTRATO_A;
END;
"""

# Lista de todos los triggers
TODOS_LOS_TRIGGERS = [
    TRIGGER_USUARIOS_UPDATE,
    TRIGGER_PERSONAS_UPDATE,
    TRIGGER_PROPIEDADES_UPDATE,
    TRIGGER_CONTRATOS_UPDATE,
]


def ejecutar_todos_los_triggers(db_manager):
    """
    Ejecuta todos los triggers de auditoria en la base de datos.

    Args:
        db_manager: Instancia de DatabaseManager
    """
    with db_manager.obtener_conexion() as conn:
        cursor = conn.cursor()

        # Primero eliminar triggers existentes si hay
        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='trigger' AND name LIKE 'trg_audit_%'"
        )
        triggers_existentes = cursor.fetchall()

        for trigger in triggers_existentes:
            cursor.execute(f"DROP TRIGGER IF EXISTS {trigger[0]}")

        # Crear nuevos triggers
        for trigger_sql in TODOS_LOS_TRIGGERS:
            cursor.execute(trigger_sql)

        conn.commit()

    pass  # print(f"[OK] Se crearon {len(TODOS_LOS_TRIGGERS)} triggers de auditoria exitosamente.") [OpSec Removed]


if __name__ == "__main__":
    from src.infraestructura.persistencia.database import DatabaseManager

    db = DatabaseManager()
    ejecutar_todos_los_triggers(db)
